config/routes.rb
CollegeCultureFit::Application.routes.draw do

  root 'welcome#index'

  get '/school_comparison/compare' => 'schools#compare'

  resources :schools

  resources :topics

  get 'about' => 'about#index'

  get 'compare' => 'schools#compare'

  get 'schoolcompare' => 'schools#schoolcompare'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true

  has_many :reference_words
  has_many :ratings

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find(params[:id])
    @ratings = Rating.all

    #Most Popular Words in Topic
    ##########################################

    holding = {"popular_words" => []}

    reference_words = @topic.reference_words
    reference_words.each do |word|
      pop_word = SchoolWordCount.find_by(reference_word_id: word.id)
      if pop_word
        holding["popular_words"] << {name: pop_word.reference_word.name, positive_count: pop_word.positive_word_count, negative_count: pop_word.negative_word_count}
      end
    end
    @popular_words = holding["popular_words"]


    ##########################################


    #School Total Post Activity in a topic
    ##########################################
    #To use in a vertical bar chart or pie chart, but is not working in a reasonable amount of time tonight
    holding_two = {"ratings_by_school" => []}
    ratings_by_school = @ratings.where(topic_id: @topic.id).all
    ratings_by_school.each do |rating|
      if rating
        holding_two["ratings_by_school"] << {name: rating.school.name, count: rating.total_post_count}
      end
    end
    @ratings_by_school = holding_two["ratings_by_school"]
  end


  ##########################################
end

app/views/topics/index.html.erb
  <h1>See What All Students are Talking About</h1>

  <h3>These are the conversation topics we've been collecting data on so far.  Click on a topic to see how each school in our database has been talking about it!</h3>

  <div id="topics-info">
    <div id="topics-list">
      <div id="topics-container">
        <% @topics.each do |topic| %>
          <%= link_to(topic_path(topic)) do %>
            <div class="topics-grid"><div><%= topic.name.gsub('_', ' ').capitalize %></div></div>
          <% end %>
        <% end %>
        <div class="topics-grid"><div>&nbsp;</div></div>
        <div class="topics-grid"><div>&nbsp;</div></div>
      </div>
    </div>

    <div id="topics-steps">
      <div class="step">
        <%= image_tag("social_media.png")%>
        <h3>College students post on social media</h3>
      </div>
      <div class="step">
        <%= image_tag("map.png")%>
        <h3>We gather posts from each campus</h3>
      </div>
      <div class="step">
        <%= image_tag("desk.png")%>
        <h3>We analyze what they're talking about</h3>
      </div>
      <div class="step">
        <%= image_tag("chart.png")%>
        <h3>You get a glimpse into campus culture</h3>
      </div>
    </div>
  </div>

app/views/topics/show.html.erb
<h1>Topic: <%= @topic.name.gsub('_', ' ').capitalize %></h1>

<div class="single-bar-chart">
  <h2>Posts about <%= @topic.name.gsub('_', ' ') %> by school</h2>
  <div id="bar-chart-topic-school" class="chart"></div>
</div>

<div class="single-bar-chart">
  <h2>Words and phrases students are using to talk about  <%= @topic.name.gsub('_', ' ') %> </h2>
  <div id="bar-chart-topic" class="chart"></div>
</div>

<script>
  var data2 = <%= @ratings_by_school.to_json.html_safe %>;
  barChart(data2);

  var data = <%= @popular_words.to_json.html_safe %>;
  barChartTopic(data);
</script>