config/routes.rb
CollegeCultureFit::Application.routes.draw do

  root 'welcome#index'

  get '/school_comparison/compare' => 'schools#compare'

  resources :schools

  resources :topics

  get 'about' => 'about#index'

  get 'compare' => 'schools#compare'

  get 'schoolcompare' => 'schools#schoolcompare'

end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name, presence: true
  validates :student_body_count, presence: true
  validates :geofeedia_id, presence: true
  after_create :create_ratings

  has_many :ratings
  has_many :original_posts
  has_many :analyzed_posts
  has_many :school_word_counts


  def create_ratings
    Topic.all.each do |topic|
      new_rating = Rating.create(topic_id: topic.id, school_id: self.id)
      new_rating.save
    end
  end

  def social_media_activity
    post_count/student_body_count.to_f
  end

  def positive_vibe_ratio
    positive_post_count/post_count.to_f
  end

  def negative_vibe_ratio
    negative_post_count/post_count.to_f
  end

  def neutral_vibe_ratio
    neutral_post_count/post_count.to_f
  end

  def mixed_vibe_ratio
    mixed_post_count/post_count.to_f
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  def index
    @schools = School.all
    @topics = Topic.all
  end

  def schoolcompare
    
    if request.xhr?
      @school = School.find(params[:school_id])
      @ratings = Rating.all.where(school_id: @school.id)
      @topics = Topic.all
      @random_pie_number = rand(1000000)
      @random_bar_number = rand(1000000)

      #General School Vibe Info      
      ##########################################

      @social_media_profile = {:positive_social_ratio => @school.positive_vibe_ratio, :negative_social_ratio => @school.negative_vibe_ratio, :neutral_social_ratio => @school.neutral_vibe_ratio}.to_json
      
      ##########################################

      #a hash of the 10 most talked about topics at each school
      ##########################################
      
      ratings_holding = {"ratings_profile" => []}
      
      sorted_ratings = @ratings.order("total_post_count desc").limit(10)

      sorted_ratings.each do |rating|
        ratings_holding["ratings_profile"] << {name: rating.topic.name, positive_count: rating.positive_post_count, negative_count: rating.negative_post_count, count: (rating.positive_post_count + rating.negative_post_count), multiplier: 3}
      end
      @ratings_profile = ratings_holding["ratings_profile"]

      ##########################################
      if params[:school_id] == "1"
        render "_school_compare", :layout => false
      elsif params[:school_id] == "2"
        render "_school_compare", :layout => false
      elsif params[:school_id] == "3"
        render "_school_compare", :layout => false
      elsif params[:school_id] == "4"
        render "_school_compare", :layout => false
      elsif params[:school_id] == "5"
        render "_school_compare", :layout => false
      end
    else
      redirect_to schools_path
    end

  end

  def compare

  end

  def show
    @school = School.find(params[:id])
    @ratings = Rating.all.where(school_id: @school.id)
    @topics = Topic.all  
    
    #General School Vibe Info
    ##########################################
    
    @social_media_profile = {:positive_social_ratio => @school.positive_vibe_ratio, :negative_social_ratio => @school.negative_vibe_ratio, :neutral_social_ratio => @school.neutral_vibe_ratio}.to_json

    ##########################################

    
    #A hash of the 10 most talked about topics at each school
    ##########################################
    ratings_holding = {"ratings_profile" => []}

    sorted_ratings = @ratings.order("total_post_count desc")

    sorted_ratings.each do |rating|
      ratings_holding["ratings_profile"] << {name: rating.topic.name, positive_count: rating.positive_post_count, negative_count: rating.negative_post_count, count: (rating.positive_post_count + rating.negative_post_count)}
    end
    @ratings_profile = ratings_holding["ratings_profile"]

    ##########################################

    
    #All School Data
    ##########################################
    # school_data = {"school_topic_posts_count" => []}

    # school_sorted_ratings = @ratings.order("total_post_count desc")

    # @school.ratings.each_with_index do |rating, index|
    #   school_data["school_topic_posts_count"] << {school: rating.school.name, name: rating.topic.name, count: rating.total_post_count, positive_post_count: rating.positive_post_count, negative_post_count: rating.negative_post_count, neutral_post_count: rating.neutral_post_count, mixed_post_count: rating.mixed_post_count, top_twenty_topic_words: []}
    #   popular_words = []
    #   school_words = SchoolWordCount.where(school_id: @school.id, topic_id: rating.topic.id).all
    #   school_words.each do |word|
    #     popular_words << {name: word.reference_word.name, count: word.word_count, positive_word_count: word.positive_word_count, negative_word_count: word.negative_word_count, mixed_word_count: word.mixed_word_count, neutral_word_count: word.neutral_word_count, multiplier: 30}
    #   end
    #   top_twenty = popular_words.sort{|least_popular,most_popular| most_popular[:count] <=> least_popular[:count]}
    #   top_twenty.first(20).each do |popular_word_hash|
    #     school_data["school_topic_posts_count"][index][:top_twenty_topic_words] << popular_word_hash
    #   end
    #   popular_words = []
    # end
    # @all_school_data = school_data["school_topic_posts_count"]
    ##########################################
  end

end

app/views/schools/_school_compare.html.erb
<div id='compare_100'>
  <h1><%= @school.name.gsub('_', ' ').titleize %></h1>

    <h2>Negativity vs Positivity</h2>
    <h3>The overall tone of the social media posts coming out of the school</h3>
  <div id="pie-chart-<%= @school.id %>-<%= @random_pie_number %>" class="pie-chart">
  </div>

  <div>
    <h3>How students at the school have been talking about different topics</h3>

    <div id="bar-chart-school-<%= @school.id %>-<%= @random_bar_number %>">
    </div>

  </div>
</div>


<script>
  var json = '<%= @social_media_profile.html_safe %>';
  var data = jQuery.parseJSON(json);
  setTimeout(function() { pieChart(data, "#pie-chart-<%= @school.id %>-<%= @random_pie_number %>"); }, 700);

  var data2 = <%= @ratings_profile.to_json.html_safe %>;
  setTimeout(function() { barChartCompare(data2, "#bar-chart-school-<%= @school.id %>-<%= @random_bar_number %>"); }, 800);

  // var allSchoolData = <%= @all_school_data.to_json.html_safe %>;
</script>

app/views/schools/compare.html.erb
<h1>Choose two schools to compare their cultural profiles!</h1>

<div class="col menu left">
  <form id="choose_school_one" action="/schoolcompare" method="GET">
    <select name="school_selector_one" id="school_one_selector">
      <option>Please choose your first school...</option>
      <option value="0">Arizona State University</option>
      <option value="1">University of Michigan, Ann Arbor</option>
      <option value="2">University of Texas, Austin</option>
      <option value="3">Michigan State University</option>
      <option value="4">University of Georgia, Athens</option>
    </select>
  </form>
</div><div class="col menu right">
  <form id="choose_school_two" action="/schoolcompare" method="GET">
    <select name="school_selector_two" id="school_two_selector">
      <option>Please choose your second school...</option>
      <option value="0">Arizona State University</option>
      <option value="1">University of Michigan, Ann Arbor</option>
      <option value="2">University of Texas, Austin</option>
      <option value="3">Michigan State University</option>
      <option value="4">University of Georgia, Athens</option>
    </select>
  </form>
</div>

<div class="col content left">
  <div id="school_one_display" class="partial">
  </div>
</div><div class="col content right">
  <div id="school_two_display" class="partial">
  </div>
</div>

<script type="text/javascript">

  $(document).on('change', '#school_one_selector', function(event) {
    event.preventDefault();
    $('#school_one_display').css({'position': 'relative', 'right': '775px', '-webkit-transition': 'all 0.7s ease-in'})

    var url = $('#choose_school_one').attr('action');
    var schoolId = (parseInt($('#school_one_selector option:selected').val()) + 1);

    $.get(url, {school_id: schoolId}, function(serverResponse) {
      var divOne = $('#school_one_display')
      divOne.css({'position': 'relative', 'right': '0px', '-webkit-transition': 'all 0.7s ease-out'})
      divOne.html(serverResponse);
    })
  });

  $(document).on('change', '#school_two_selector', function(event) {
    event.preventDefault();
    $('#school_two_display').css({'position': 'relative', 'left': '775px', '-webkit-transition': 'all 0.7s ease-in'})

    var url = $('#choose_school_two').attr('action');
    var schoolId = (parseInt($('#school_two_selector option:selected').val()) + 1);

    $.get(url, {school_id: schoolId}, function(serverResponse) {
      var divTwo = $('#school_two_display')
      divTwo.css({'position': 'relative', 'left': '0px', '-webkit-transition': 'all 0.7s ease-out'})
        divTwo.html(serverResponse);
    });
});

</script>

app/views/schools/index.html.erb
<h1>See What Schools are Talking About</h1>

<div id="schools-info">

	<div id="schools-list">
		<div id="schools-container">
		  <%@schools.reverse.each do |school|%>
		    <div><%= link_to(image_tag("#{school.geofeedia_id}.png"), school_path(school)) %></div>
		  <%end%>
		</div>
	</div>

	<div id="schools-steps">
			<div class="step">
				<%= image_tag("social_media.png")%>
				<h3>College students post on social media</h3>
			</div>
			<div class="step">
				<%= image_tag("map.png")%>
				<h3>We gather posts from each campus</h3>
			</div>
			<div class="step">
				<%= image_tag("desk.png")%>
				<h3>We analyze what they're talking about</h3>
			</div>
			<div class="step">
				<%= image_tag("chart.png")%>
				<h3>You get a glimpse into campus culture</h3>
			</div>
		</div>
	</div>

</div>

app/views/schools/show.html.erb
<h1><%= @school.name %></h1>

<div class="chart-div">
    <h2>Negativity vs Positivity</h2>
    <h3>The overall tone of the social media posts coming out of <%= @school.name %></h3>
  <div id="pie-chart" class="pie-chart"></div>
</div>


<div class="chart-div">
  <h2>Topics</h2>
  <h3>How students at <%= @school.name %> have been talking about different topics</h3>
  <div id="bar-chart-school" class="bar-chart"></div>
</div>

<br><br><br><br><br><br><br><br>

<script>
  var json = '<%= @social_media_profile.html_safe %>';
  var data = jQuery.parseJSON(json);
  pieChart(data, "#pie-chart");

  var data2 = <%= @ratings_profile.to_json.html_safe %>;
  barChartSchool(data2, "#bar-chart-school");
</script>