config/routes.rb
CollegeCultureFit::Application.routes.draw do

  root 'welcome#index'

  get '/school_comparison/compare' => 'schools#compare'

  resources :schools

  resources :topics

  get 'about' => 'about#index'

  get 'compare' => 'schools#compare'

  get 'schoolcompare' => 'schools#schoolcompare'

end

app/views/layouts/_footer.html.erb
<div id="footer">
  trUism is an app produced by Dev Bootcamp students Lauren Scott, Jess Unrein, Daniel Lu, Jay Rogers, and Andrew Wittrock.
</div>

app/views/layouts/_header.html.erb
<nav>
  <a href="/"><%= image_tag("truism_logo_white.png", id: "nav-bar-logo")%></a>
  <div id="nav-links">
    <%= link_to "About", controller: "about" %>
    <%= link_to "Topics", controller: "topics" %>
    <%= link_to "Compare Schools", compare_path %>
    <%= link_to "Schools", controller: "schools" %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>trUism</title>
    <%= stylesheet_link_tag "normalize", media: "all", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
    <script src="//use.edgefonts.net/quicksand;lato:n1,i1,n3,i3,n4,i4,n7,i7,n9,i9.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Quattrocento+Sans:400,700,400italic' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <div id="transparent-background">
      <% unless @disable_nav %>
        <%= render 'layouts/header'%>
        <div class="container">
                <% end %>

          <%= yield %>

        </div>
        <%= render 'layouts/footer'%>
    </div>
  </body>
</html>